services:

  postgres:
    image: postgres:16.3
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    volumes:
      - local_pgdata:/var/lib/postgresql/data 
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5     


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    depends_on:
      postgres:
        condition: service_healthy    
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: abbassizied@outlook.fr
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    deploy:
      resources:
        limits:
          memory: 512M

  # spring service
  spring-petclinic:
    image: ziedab/spring-petclinic
    container_name: spring-petclinic-cont
    ports:
      - "8097:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres 
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update      
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-I", "http://spring-petclinic:8097"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes: 
  local_pgdata:
  pgadmin-data:
   